### ISSUE TITLE
添加maven 文件之后，是不是就可以直接使用方法了。

### ISSUE THREAD

**Issue by LeeWaTa** [Ijiran/legal-holidays#1]
LegalHolidaysUtil   54行

LegalHolidaysCache.LEGAL_HOLIDAY_MAP  为空

是还需要 添加什么初始化配置吗

**Comment by Ijiran** [comment]
需要在程序开启时，将节假日信息维护到LEGAL_HOLIDAY_MAP中。

请看一下这个例子：src/main/java/top/pxyz/holidays/config/LegalHolidaysConfigExample.java

**Comment by Ijiran** [comment]
LEGAL_HOLIDAY_MAP 是节假日信息，除了内置信息外，其他年份的节假日信息需要手动内置。

**Comment by LeeWaTa** [comment]
原来还得自己手动配置是吧，我以为是 添加 maven 之后，会自动处理。

**Comment by Ijiran** [comment]
2024年的节假日刚出来，比如想要查2025年节假日的话，就需要手动加载信息了。

**Comment by Ijiran** [comment]
<img width="326" alt="image" src="https://github.com/Ijiran/legal-holidays/assets/28706330/15556535-4a2e-46e6-a3cf-befb6ec7a174">
目前只内置了这几年的节假日信息

**Comment by LeeWaTa** [comment]
好滴，谢谢啦
